/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_iviking_app_jni_JNIUtils */

#ifndef _Included_cn_iviking_app_jni_JNIUtils
#define _Included_cn_iviking_app_jni_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_iviking_app_jni_JNIUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_iviking_app_jni_JNIUtils_getString
  (JNIEnv *, jobject);

/*
 * Class:     cn_iviking_app_jni_JNIUtils
 * Method:    getSymbol
 * Signature: ([BLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_cn_iviking_app_jni_JNIUtils_getSymbol
  (JNIEnv *, jobject, jbyteArray, jstring, jlong, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
